import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

/**
 * Replaces eslint-config-erb, which went with the Electron React Boilerplate
 * toolchain.
 *
 * Type-aware linting is deliberately not enabled. It would duplicate what
 * `npm run typecheck` already reports and roughly triple lint time on a tree
 * this size. Rules that need type information belong there.
 *
 * The severity split is intentional: anything that indicates a real defect is an
 * error, so `npm run lint` fails on it, while long-standing stylistic drift in
 * this 2022 codebase is a warning. That keeps the command usable as a gate today
 * instead of failing on hundreds of pre-existing issues. Promote warnings to
 * errors as they get cleared.
 */
export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'out/**',
      'release/**',
      'engine/node_modules/**',
      'assets/engine-dist/**',
      // Generated by `npm run engine:embed` from engine/src, which is linted
      // in its own right.
      'src/components/Storyteller/embedded/**',
      // Copied from engine/assets by `npm run engine:styles`.
      'src/styles/engine.less',
      'src/styles/engine-editor.less',
      // The original docs.elmstory.com recovered from archive.org: third-party
      // scripts saved alongside the pages, reference material rather than source.
      // Git-ignored, but eslint walks the working tree, and it reported 14352
      // errors from them.
      'Docs/**'
    ]
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, ...globals.node }
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...reactHooks.configs.recommended.rules,

      'react/prop-types': 'off',
      'react/display-name': 'off',
      // Reported far more precisely by `npm run typecheck`, which already has
      // noUnusedLocals and noUnusedParameters enabled.
      '@typescript-eslint/no-unused-vars': 'off',

      // `condition && doSomething()` as a statement is the dominant idiom in
      // this codebase, and these options are what the rule provides for it.
      // Genuinely unused expressions are still reported.
      '@typescript-eslint/no-unused-expressions': [
        'error',
        { allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true }
      ],

      // Pre-existing patterns, each appearing too widely to gate on. Left
      // visible so they can be worked down. Counts at the time of writing:
      //
      //   no-useless-catch                301  `catch (error) { throw error }`
      //   react-hooks/exhaustive-deps     148
      //   no-explicit-any                  57
      //   react-hooks/set-state-in-effect  55
      //   ban-ts-comment                   43
      //   no-case-declarations             26
      //   react-hooks/refs                 26
      //   react/no-unescaped-entities      26
      'no-useless-catch': 'warn',
      'no-case-declarations': 'warn',
      // Reported where a `let` shares a declaration with a sibling that is
      // reassigned, so satisfying it means splitting the statement. Stylistic.
      'prefer-const': 'warn',
      // Flags the defensive `let x = undefined` that precedes a try/catch. The
      // rule does not account for the throw path, where the initial value is
      // what the catch block sees.
      'no-useless-assignment': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'preserve-caught-error': 'warn',
      'react/no-unescaped-entities': 'warn',
      'react/no-children-prop': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',

      // rules-of-hooks once flagged 89 sites across 21 files, nearly all of them
      // an early `return null` placed above a component's hook calls, which
      // changes hook order between renders. All of them are fixed, so this is an
      // error rather than a warning: it now gates against reintroducing the
      // pattern instead of cataloguing it. The two below are still real
      // correctness risks, not style, but remain too widespread to gate on.
      'react-hooks/rules-of-hooks': 'error',

      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/static-components': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn'
    }
  },

  {
    // tsconfig.json uses the classic JSX transform for the editor, so React has
    // to be in scope there even though the Vite build uses the automatic
    // runtime. engine/tsconfig.json uses "react-jsx", so it does not.
    files: ['src/**/*.tsx'],
    rules: { 'react/react-in-jsx-scope': 'error' }
  },

  {
    files: ['engine/src/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
    rules: { 'react/react-in-jsx-scope': 'off' }
  },

  {
    files: ['src/main.ts', 'src/menu.ts', 'scripts/**', '*.config.{ts,mts,mjs}'],
    languageOptions: { globals: globals.node }
  },

  {
    // Plain-JavaScript tooling does not pick up the TypeScript block's rules,
    // so the same allowances are repeated here.
    files: ['scripts/**/*.{js,mjs}', '*.config.{js,mjs}'],
    languageOptions: {
      globals: globals.node,
      parserOptions: { ecmaVersion: 'latest', sourceType: 'module' }
    },
    rules: {
      // typescript-eslint's recommended set applies to every file and replaces
      // the core rule, so the plugin's name is the one that has to be set.
      '@typescript-eslint/no-unused-expressions': [
        'error',
        { allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true }
      ]
    }
  },

  {
    files: ['src/**/*.{test,spec}.{ts,tsx}', 'src/__tests__/**'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } }
  },

  // Formatting belongs to Prettier; this must stay last.
  prettier
)
